/* ============================================================
   Mock data for SDD Hub
   A tech lead supervising local Claude Code agents on a SaaS
   transcription product called "Plover", plus a few sister repos.
   ============================================================ */

const NOW = new Date('2026-05-14T10:42:00Z');

const fmtAgo = (date) => {
  const d = (typeof date === 'string') ? new Date(date) : date;
  const sec = Math.floor((NOW - d) / 1000);
  if (sec < 60) return sec + 's';
  if (sec < 3600) return Math.floor(sec / 60) + 'm';
  if (sec < 86400) return Math.floor(sec / 3600) + 'h';
  return Math.floor(sec / 86400) + 'd';
};

const AGENTS = {
  'agent-01': { id: 'agent-01', initials: 'CC', name: 'cc-main',     host: 'krait.local',  status: 'busy',  pid: 28471 },
  'agent-02': { id: 'agent-02', initials: 'CC', name: 'cc-billing',  host: 'krait.local',  status: 'busy',  pid: 28612 },
  'agent-03': { id: 'agent-03', initials: 'CC', name: 'cc-mobile',   host: 'lyre.local',   status: 'idle',  pid: 11203 },
  'agent-04': { id: 'agent-04', initials: 'CC', name: 'cc-audit',    host: 'krait.local',  status: 'busy',  pid: 28944 },
  'agent-05': { id: 'agent-05', initials: 'CC', name: 'cc-ledger',   host: 'sable.local',  status: 'idle',  pid:  5512 },
};

/* ------------------------------------------------------------
   WORKSPACES
   ------------------------------------------------------------ */

const WORKSPACES = [
  {
    id: 'plover',
    name: 'plover',
    path: '~/code/plover',
    description: 'meeting transcription + shareable notes',
    pinned: true,
    lastActivity: '2026-05-14T10:41:12Z',
    agents: ['agent-01', 'agent-02', 'agent-04'],
    counts: {
      targetsAwaitingUser: 2,
      targetsAwaitingAgent: 1,
      targetsReady: 1,
      targetsDraft: 1,
      specs: 4,
      specItems: 23,
      openGaps: 6,
      staleAuditDomains: 1,
      workPending: 5,
      workInProgress: 2,
      workBlocked: 1,
      workDoneToday: 3,
    },
  },
  {
    id: 'plover-mobile',
    name: 'plover-mobile',
    path: '~/code/plover-mobile',
    description: 'react-native client',
    lastActivity: '2026-05-14T08:14:00Z',
    agents: ['agent-03'],
    counts: {
      targetsAwaitingUser: 0,
      targetsAwaitingAgent: 0,
      targetsReady: 0,
      targetsDraft: 1,
      specs: 2,
      specItems: 9,
      openGaps: 0,
      staleAuditDomains: 0,
      workPending: 0,
      workInProgress: 0,
      workBlocked: 0,
      workDoneToday: 1,
    },
  },
  {
    id: 'ledger-cli',
    name: 'ledger-cli',
    path: '~/code/ledger-cli',
    description: 'maintenance — accounting tool',
    lastActivity: '2026-05-13T19:02:00Z',
    agents: ['agent-05'],
    counts: {
      targetsAwaitingUser: 0,
      targetsAwaitingAgent: 0,
      targetsReady: 0,
      targetsDraft: 0,
      specs: 3,
      specItems: 14,
      openGaps: 3,
      staleAuditDomains: 0,
      workPending: 2,
      workInProgress: 0,
      workBlocked: 0,
      workDoneToday: 0,
    },
  },
  {
    id: 'vault-rs',
    name: 'vault-rs',
    path: '~/code/vault-rs',
    description: 'new — encrypted note vault in rust',
    lastActivity: '2026-05-14T09:30:00Z',
    agents: [],
    counts: {
      targetsAwaitingUser: 1,
      targetsAwaitingAgent: 0,
      targetsReady: 0,
      targetsDraft: 2,
      specs: 1,
      specItems: 4,
      openGaps: 0,
      staleAuditDomains: 0,
      workPending: 0,
      workInProgress: 0,
      workBlocked: 0,
      workDoneToday: 0,
    },
  },
];

/* ------------------------------------------------------------
   PLOVER — specs, targets, gaps, work items
   This is the workspace the prototype is centered around.
   ------------------------------------------------------------ */

const SPECS = [
  {
    id: 'SPEC-auth',
    domain: 'authentication',
    abbrev: 'auth',
    version: 'a3f9c812',
    items: [
      {
        id: 'SPEC-auth-001',
        title: 'Admin actions require two-factor verification',
        status: 'active',
        body: 'All admin-privileged operations MUST verify a second factor before proceeding. The factor must be validated within the current session; cross-session caching is not permitted.',
        refs: [{ kind: 'gap', id: 'GAP-auth-001' }, { kind: 'wi', id: 'WI-auth-001' }],
      },
      {
        id: 'SPEC-auth-002',
        title: 'Session tokens must not persist beyond logout',
        status: 'active',
        body: 'On user-initiated or system-triggered logout, all session tokens — access, refresh, and any cached credentials — MUST be invalidated server-side and cleared from client storage within the same request.',
        refs: [{ kind: 'gap', id: 'GAP-auth-002' }, { kind: 'wi', id: 'WI-auth-002' }],
      },
      {
        id: 'SPEC-auth-003',
        title: 'Refresh token rotation on every refresh',
        status: 'active',
        body: 'Refresh tokens MUST rotate on each use. Reuse of a previously rotated refresh token MUST invalidate the entire token family and force re-authentication.',
        refs: [],
      },
      {
        id: 'SPEC-auth-004',
        title: 'Admin actions are audit-logged with actor + reason',
        status: 'active',
        body: 'Every admin action MUST emit an audit log entry containing the actor user id, action name, target resource, MFA verification token id, and a free-form reason field supplied by the actor.',
        refs: [{ kind: 'gap', id: 'GAP-auth-003' }],
      },
      {
        id: 'SPEC-auth-005',
        title: 'Account lockout after 5 failed attempts in 15 minutes',
        status: 'active',
        body: 'After 5 failed login attempts in any sliding 15-minute window, the account MUST be locked for 30 minutes. Lockout MUST be enforced per-account, not per-IP.',
        refs: [],
      },
    ],
  },
  {
    id: 'SPEC-trans',
    domain: 'transcription',
    abbrev: 'trans',
    version: 'b7d2e941',
    items: [
      {
        id: 'SPEC-trans-001',
        title: 'Audio uploads are bounded to 4 hours per file',
        status: 'active',
        body: 'Single uploaded files MUST be rejected at the API boundary if their duration exceeds 4 hours. Rejection MUST occur before any transcoding work is scheduled.',
        refs: [],
      },
      {
        id: 'SPEC-trans-002',
        title: 'Transcription jobs are retryable up to 3 times',
        status: 'active',
        body: 'Failed transcription jobs MUST be retried automatically up to 3 times with exponential backoff (1m, 5m, 25m). After the third failure, the job is marked permanently failed and surfaced to the user.',
        refs: [{ kind: 'gap', id: 'GAP-trans-001' }, { kind: 'wi', id: 'WI-trans-001' }],
      },
      {
        id: 'SPEC-trans-003',
        title: 'Speaker diarization runs by default',
        status: 'active',
        body: 'Diarization MUST be enabled by default for all transcription jobs. Users with the "single-speaker" preference may opt out per-upload.',
        refs: [],
      },
      {
        id: 'SPEC-trans-004',
        title: 'Auto-generated summaries quote at least one verbatim line',
        status: 'active',
        body: 'Each AI-generated summary MUST cite at least one verbatim quotation from the transcript with a timestamp anchor, so users can trace synthesis back to source.',
        refs: [{ kind: 'gap', id: 'GAP-trans-002' }],
      },
    ],
  },
  {
    id: 'SPEC-billing',
    domain: 'billing',
    abbrev: 'bill',
    version: 'c4e1f205',
    items: [
      {
        id: 'SPEC-bill-001',
        title: 'Free tier capped at 5 hours of audio per month',
        status: 'active',
        body: 'Accounts on the free tier MUST be prevented from exceeding 5 hours of cumulative transcribed audio per calendar month. Excess uploads MUST be rejected with a clear paywall response.',
        refs: [{ kind: 'gap', id: 'GAP-bill-001' }],
      },
      {
        id: 'SPEC-bill-002',
        title: 'Subscription downgrades take effect at period end',
        status: 'active',
        body: 'When a user downgrades a paid plan, the existing tier MUST remain active until the end of the current billing period. The downgraded tier becomes effective at the next renewal.',
        refs: [],
      },
      {
        id: 'SPEC-bill-003',
        title: 'Card decline grace period of 7 days',
        status: 'active',
        body: 'When a renewal payment is declined, the user retains full access for 7 days. Three retry attempts MUST occur in that window. If unresolved by day 7, the account drops to read-only.',
        refs: [{ kind: 'gap', id: 'GAP-bill-002' }, { kind: 'wi', id: 'WI-bill-001' }],
      },
    ],
  },
  {
    id: 'SPEC-share',
    domain: 'sharing',
    abbrev: 'share',
    version: 'e8b91d44',
    items: [
      {
        id: 'SPEC-share-001',
        title: 'Public share links expire after 30 days by default',
        status: 'active',
        body: 'Newly created public share links MUST default to a 30-day expiration. Owners may shorten this but not extend it without re-authenticating.',
        refs: [],
      },
      {
        id: 'SPEC-share-002',
        title: 'Revoked links return 410 Gone, not 404',
        status: 'active',
        body: 'Explicitly revoked share links MUST respond with HTTP 410 to distinguish them from never-existed links (404). The response body MUST NOT leak resource metadata.',
        refs: [{ kind: 'gap', id: 'GAP-share-001' }],
      },
    ],
  },
];

const TARGETS = [
  {
    id: 'TGT-011',
    status: 'awaiting-user',
    domain: 'authentication',
    title: 'Lock the account, not the IP — but soft on shared networks',
    created: '2026-05-14T09:18:00Z',
    statement: 'On 5 failed login attempts within 15 minutes from the same account, lock the account for 30 minutes. Account-level lockout — not IP — because users on shared networks (offices, cafes) shouldn\'t be punished for someone else\'s typos.',
    domainAbbrev: 'auth',
    dialog: [
      {
        who: 'user',
        date: '2026-05-14',
        text: 'We need an account lockout policy. Brute-force attempts on /login are showing up in the logs. I want to lock the account itself, not the IP — too many false positives on shared networks.',
      },
      {
        who: 'agent',
        date: '2026-05-14',
        text: 'A few things to nail down before I write this:\n\n1. What counts the failed attempt — wrong password only, or also wrong username (i.e., unknown user)?\n2. What\'s the lockout window — fixed (e.g. 30min) or escalating?\n3. How does the user unlock — wait it out, email reset link, or both?\n\nAlso: should locked accounts receive an email notifying them, in case it\'s a real attacker hitting their account?',
      },
    ],
  },
  {
    id: 'TGT-012',
    status: 'awaiting-user',
    domain: 'sharing',
    title: 'Password-protected share links',
    created: '2026-05-13T16:30:00Z',
    statement: 'Add an optional password gate on public share links. The viewer enters a password before the transcript renders. Password is set at creation, not changeable; rotating means a new link.',
    domainAbbrev: 'share',
    dialog: [
      {
        who: 'user',
        date: '2026-05-13',
        text: 'Sales team keeps asking for password-protected share links. Right now the only options are "public" or "logged-in users only."',
      },
      {
        who: 'agent',
        date: '2026-05-13',
        text: 'A couple of clarifications:\n\n1. Is the password a per-link secret (set once, never rotated), or is rotation allowed?\n2. Where is the password stored — hashed at rest, or held in the link\'s URL fragment so the server never sees it?\n3. How does this compose with the 30-day expiration in SPEC-share-001? Does a password override expiration, or do both apply?',
      },
      {
        who: 'user',
        date: '2026-05-14',
        text: 'No rotation — if you want a new password, generate a new link. Hash at rest, bcrypt is fine. Both rules apply: link expires at 30 days AND requires the password until then.',
      },
      {
        who: 'agent',
        date: '2026-05-14',
        text: 'Got it — that\'s enough to commit. One last gap: how should the failure mode look? On wrong password do we respond with 401 + a generic message, or rate-limit attempts per link? I\'ll assume 401 with a 5-attempt-per-hour-per-IP throttle unless you push back.\n\nProposed Current statement:\n\n> Public share links MAY require an optional viewer password set at creation time. The password is hashed at rest (bcrypt) and never displayed after creation. Wrong-password responses return HTTP 401 with no resource metadata. Failed attempts are rate-limited to 5 per hour per IP per link. The 30-day expiration in SPEC-share-001 continues to apply unchanged.\n\nAccept this, or revise and flip status back to awaiting-agent.',
      },
    ],
  },
  {
    id: 'TGT-013',
    status: 'awaiting-agent',
    domain: 'transcription',
    title: 'Resume interrupted uploads',
    created: '2026-05-14T08:55:00Z',
    statement: 'Long uploads (>30min audio) currently fail completely on network blips. Add resumable upload — tus protocol or similar — so the client can pick up where it left off without re-uploading from byte 0.',
    domainAbbrev: 'trans',
    dialog: [
      {
        who: 'user',
        date: '2026-05-14',
        text: 'Long uploads (>30min audio) currently fail completely on network blips. Add resumable upload — tus protocol or similar — so the client can pick up where it left off without re-uploading from byte 0.',
      },
    ],
  },
  {
    id: 'TGT-014',
    status: 'ready',
    domain: 'billing',
    title: 'Annual billing — 20% discount',
    created: '2026-05-12T11:00:00Z',
    statement: 'Offer an annual billing option for paid tiers at a 20% discount vs monthly. Annual subscribers can downgrade per the existing rules (effective at period end). On cancellation mid-year, no refund — access continues to period end.',
    domainAbbrev: 'bill',
    dialog: [
      { who: 'user', date: '2026-05-12', text: 'Want to add annual billing at 20% off monthly. Stripe supports it natively.' },
      { who: 'agent', date: '2026-05-12', text: 'Should mid-year cancellation refund the unused portion, or hold access to period-end with no refund?' },
      { who: 'user', date: '2026-05-13', text: 'No refund. Access continues to period end, same as monthly downgrades.' },
      {
        who: 'agent',
        date: '2026-05-13',
        text: 'That composes cleanly with SPEC-bill-002. Proposing the following:\n\n> Paid tiers MAY be billed annually at 20% off the monthly rate. Annual subscriptions follow the same downgrade and cancellation rules as monthly (effective at period end, no refund for unused time).\n\nFlipping to ready.',
      },
    ],
  },
  {
    id: 'TGT-015',
    status: 'draft',
    domain: 'authentication',
    title: '(draft) SSO via Google for the team plan',
    created: '2026-05-14T10:02:00Z',
    statement: '',
    domainAbbrev: 'auth',
    dialog: [],
  },
];

const GAPS = [
  {
    id: 'GAP-auth-001',
    specItem: 'SPEC-auth-001',
    domain: 'authentication',
    abbrev: 'auth',
    status: 'open',
    discovered: '2026-05-12T14:30:00Z',
    auditVersion: 'a3f9c812',
    title: 'Admin handler bypasses MFA verification',
    location: 'src/auth/admin.py:142',
    reasoning: '`execute_admin_action()` calls `_require_role("admin")` but never checks `session.mfa_verified_at` against the current request window — passes through if the user has the role.',
    codeContext: {
      lang: 'python',
      lines: [
        { n: 138, src: 'def execute_admin_action(req: AdminRequest) -> Response:' },
        { n: 139, src: '    user = current_user()' },
        { n: 140, src: '    _require_role("admin", user)' },
        { n: 141, src: '' },
        { n: 142, src: '    # ← no MFA check here; proceeds directly to dispatch', hl: true },
        { n: 143, src: '    return dispatch(req.action, req.payload, actor=user)' },
        { n: 144, src: '' },
      ],
    },
    closedBy: null,
  },
  {
    id: 'GAP-auth-002',
    specItem: 'SPEC-auth-002',
    domain: 'authentication',
    abbrev: 'auth',
    status: 'open',
    discovered: '2026-05-12T14:31:00Z',
    auditVersion: 'a3f9c812',
    title: 'Logout does not clear the in-memory token cache',
    location: 'src/auth/session.py:67',
    reasoning: '`logout()` deletes the refresh token row but leaves `_token_cache[user_id]` populated for the remainder of the process lifetime.',
    codeContext: {
      lang: 'python',
      lines: [
        { n: 63, src: 'def logout(user_id: int) -> None:' },
        { n: 64, src: '    with db.transaction():' },
        { n: 65, src: '        db.execute("DELETE FROM refresh_tokens WHERE user_id = ?", user_id)' },
        { n: 66, src: '    audit.log("user.logout", actor=user_id)' },
        { n: 67, src: '    # ← _token_cache still contains the cached session', hl: true },
        { n: 68, src: '    return' },
      ],
    },
    closedBy: 'WI-auth-002',
  },
  {
    id: 'GAP-auth-003',
    specItem: 'SPEC-auth-004',
    domain: 'authentication',
    abbrev: 'auth',
    status: 'open',
    discovered: '2026-05-12T14:31:30Z',
    auditVersion: 'a3f9c812',
    title: 'Admin audit log omits the supplied reason',
    location: 'src/audit/logger.py:88',
    reasoning: '`log_admin_action()` records actor + action + target but drops `reason` from the payload signature. The spec mandates a free-form reason field.',
    codeContext: {
      lang: 'python',
      lines: [
        { n: 84, src: 'def log_admin_action(actor: int, action: str, target: str) -> None:' },
        { n: 85, src: '    _append({' },
        { n: 86, src: '        "actor": actor, "action": action, "target": target,' },
        { n: 87, src: '        "ts": utcnow().isoformat(),' },
        { n: 88, src: '    })  # ← no reason field — silently dropped at the API layer too', hl: true },
        { n: 89, src: '' },
      ],
    },
    closedBy: null,
  },
  {
    id: 'GAP-trans-001',
    specItem: 'SPEC-trans-002',
    domain: 'transcription',
    abbrev: 'trans',
    status: 'open',
    discovered: '2026-05-13T09:15:00Z',
    auditVersion: 'b7d2e941',
    title: 'Retry backoff is linear, not exponential',
    location: 'src/jobs/transcribe.py:204',
    reasoning: 'Retry delay is hardcoded to 60s between attempts (3 retries × 60s). Spec requires exponential 1m / 5m / 25m.',
    codeContext: {
      lang: 'python',
      lines: [
        { n: 200, src: 'RETRY_LIMIT = 3' },
        { n: 201, src: 'RETRY_DELAY_S = 60   # ← linear backoff', hl: true },
        { n: 202, src: '' },
        { n: 203, src: 'def reschedule(job: Job) -> None:' },
        { n: 204, src: '    job.retry_at = utcnow() + timedelta(seconds=RETRY_DELAY_S)' },
        { n: 205, src: '    db.save(job)' },
      ],
    },
    closedBy: 'WI-trans-001',
  },
  {
    id: 'GAP-trans-002',
    specItem: 'SPEC-trans-004',
    domain: 'transcription',
    abbrev: 'trans',
    status: 'open',
    discovered: '2026-05-13T09:16:00Z',
    auditVersion: 'b7d2e941',
    title: 'Summary generator does not emit verbatim quotes',
    location: 'src/ai/summarize.py:55',
    reasoning: 'Prompt instructs "synthesize the meeting" but never asks for verbatim citations or timestamp anchors. Output JSON has no `quotes` field.',
    codeContext: {
      lang: 'python',
      lines: [
        { n: 51, src: 'PROMPT = """' },
        { n: 52, src: 'You are summarizing a meeting transcript.' },
        { n: 53, src: 'Give a 5-bullet summary of decisions and action items.' },
        { n: 54, src: '"""' },
        { n: 55, src: '# ← no instruction to cite verbatim with timestamps; no quotes in output', hl: true },
        { n: 56, src: '' },
      ],
    },
    closedBy: null,
  },
  {
    id: 'GAP-bill-001',
    specItem: 'SPEC-bill-001',
    domain: 'billing',
    abbrev: 'bill',
    status: 'open',
    discovered: '2026-05-10T20:00:00Z',
    auditVersion: 'c4e1f205',
    title: 'Free-tier hour cap is checked weekly, not monthly',
    location: 'src/billing/quota.py:39',
    reasoning: '`enforce_free_quota()` resets the counter every 7 days. Spec requires per-calendar-month enforcement.',
    codeContext: {
      lang: 'python',
      lines: [
        { n: 35, src: 'FREE_HOURS = 5' },
        { n: 36, src: 'WINDOW_DAYS = 7   # ← spec says calendar month', hl: true },
        { n: 37, src: '' },
        { n: 38, src: 'def enforce_free_quota(user: User, hours: float) -> Decision:' },
        { n: 39, src: '    used = sum_hours_since(user.id, days_ago=WINDOW_DAYS)' },
      ],
    },
    closedBy: null,
  },
  {
    id: 'GAP-bill-002',
    specItem: 'SPEC-bill-003',
    domain: 'billing',
    abbrev: 'bill',
    status: 'open',
    discovered: '2026-05-11T11:20:00Z',
    auditVersion: 'c4e1f205',
    title: 'Card decline downgrades immediately, no grace period',
    location: 'src/billing/webhook.py:118',
    reasoning: 'On Stripe `invoice.payment_failed`, the account is moved to `read_only` in the same handler call. Spec mandates a 7-day grace with 3 retries.',
    codeContext: {
      lang: 'python',
      lines: [
        { n: 115, src: '@on("invoice.payment_failed")' },
        { n: 116, src: 'def handle_decline(event: StripeEvent) -> None:' },
        { n: 117, src: '    account = Account.get(event.customer)' },
        { n: 118, src: '    account.tier = "read_only"   # ← immediate, no grace', hl: true },
        { n: 119, src: '    account.save()' },
      ],
    },
    closedBy: 'WI-bill-001',
  },
  {
    id: 'GAP-share-001',
    specItem: 'SPEC-share-002',
    domain: 'sharing',
    abbrev: 'share',
    status: 'open',
    discovered: '2026-05-09T13:00:00Z',
    auditVersion: 'e8b91d44',
    title: 'Revoked links 404 instead of 410',
    location: 'src/sharing/view.py:24',
    reasoning: 'Endpoint returns 404 for any link not found in the active table. Revoked links land in a separate `revoked_links` table that is never consulted.',
    codeContext: {
      lang: 'python',
      lines: [
        { n: 20, src: 'def view(slug: str) -> Response:' },
        { n: 21, src: '    link = ShareLink.find(slug=slug)' },
        { n: 22, src: '    if not link:' },
        { n: 23, src: '        return Response(status=404)   # ← always 404, never 410', hl: true },
        { n: 24, src: '    return render(link)' },
      ],
    },
    closedBy: null,
  },
];

const WORK_ITEMS = [
  {
    id: 'WI-auth-001',
    gapId: 'GAP-auth-001',
    title: 'Add MFA verification to admin action handler',
    status: 'in-progress',
    domain: 'authentication',
    agent: 'agent-01',
    created: '2026-05-12T16:00:00Z',
    scope: 'src/auth/admin.py — verify `session.mfa_verified_at` is within MFA_TTL before dispatch',
    acceptance: [
      'MFA check at handler entry; rejects calls where verification is missing or older than 5 minutes',
      'Unit: MFA absent → 401, no audit log',
      'Unit: MFA present + fresh → success, audit log emitted with verification token id',
      'Unit: MFA present but stale → 401',
    ],
    progressNote: 'Wrote rejection path. Wiring up the fresh-MFA check now.',
  },
  {
    id: 'WI-auth-002',
    gapId: 'GAP-auth-002',
    title: 'Clear in-memory token cache on logout',
    status: 'pending',
    domain: 'authentication',
    agent: null,
    created: '2026-05-12T16:10:00Z',
    scope: 'src/auth/session.py — `logout()` must purge `_token_cache[user_id]` and any derived caches',
    acceptance: [
      'Cache entry removed in same `logout()` call',
      'Unit: cache populated → logout → cache miss for that user',
      'Integration: logout endpoint hit, subsequent authenticated request fails fast',
    ],
  },
  {
    id: 'WI-trans-001',
    gapId: 'GAP-trans-001',
    title: 'Replace linear retry backoff with exponential schedule',
    status: 'in-progress',
    domain: 'transcription',
    agent: 'agent-04',
    created: '2026-05-13T10:00:00Z',
    scope: 'src/jobs/transcribe.py — schedule retries at 60s, 300s, 1500s after the prior failure',
    acceptance: [
      'Retries fire at exactly 1m / 5m / 25m after each failure',
      'Unit: failure #1 → next-retry-at = now + 60s',
      'Unit: failure #2 → +300s; failure #3 → +1500s',
      'Unit: failure #4 → job marked permanently_failed',
    ],
    progressNote: 'Tests passing for retry #1 and #2; working on the permanent-fail branch.',
  },
  {
    id: 'WI-bill-001',
    gapId: 'GAP-bill-002',
    title: 'Implement 7-day decline grace window',
    status: 'blocked',
    domain: 'billing',
    agent: 'agent-02',
    created: '2026-05-12T17:30:00Z',
    scope: 'src/billing/webhook.py + new `grace_period` table — on payment_failed, enter grace; on grace expiry, downgrade',
    acceptance: [
      'On payment_failed: grace row created, account.tier unchanged',
      'Three retry events scheduled at +2d, +4d, +6d',
      'If any retry succeeds: grace row deleted, tier unchanged',
      'If grace_started_at + 7d passes with no success: tier → read_only',
    ],
    blockedReason: 'Waiting on TGT-014 (annual billing) to land — the grace logic needs to know whether the next renewal is monthly or annual to schedule the retries.',
    progressNote: 'Schema and webhook entry written; retry scheduler stub in place.',
  },
  {
    id: 'WI-share-001',
    gapId: 'GAP-share-001',
    title: 'Return 410 Gone for revoked share links',
    status: 'pending',
    domain: 'sharing',
    agent: null,
    created: '2026-05-13T11:00:00Z',
    scope: 'src/sharing/view.py — consult `revoked_links` before responding 404',
    acceptance: [
      'Active link → 200 with content',
      'Revoked link → 410, body contains no resource metadata',
      'Never-existed link → 404',
    ],
  },
  {
    id: 'WI-trans-002',
    gapId: 'GAP-trans-002',
    title: 'Summary prompt requires verbatim quotations',
    status: 'pending',
    domain: 'transcription',
    agent: null,
    created: '2026-05-13T11:30:00Z',
    scope: 'src/ai/summarize.py — update prompt + JSON schema to require `quotes: [{ts, text}]`',
    acceptance: [
      'Prompt requires at least one verbatim quotation with timestamp',
      'Output JSON includes `quotes` array, non-empty',
      'Integration: 20 sample transcripts → 100% have ≥1 quote',
    ],
  },
  {
    id: 'WI-auth-003',
    gapId: 'GAP-auth-003',
    title: 'Thread `reason` through admin audit pipeline',
    status: 'pending',
    domain: 'authentication',
    agent: null,
    created: '2026-05-13T15:00:00Z',
    scope: 'src/audit/logger.py + API request schema — accept `reason` on admin endpoints, persist it',
    acceptance: [
      'Admin endpoints require non-empty `reason` field; 400 if missing',
      'Audit log row contains the reason verbatim',
      'Migration adds `reason` column with NOT NULL constraint',
    ],
  },
  /* Recently done (today) */
  {
    id: 'WI-auth-004',
    gapId: 'GAP-auth-004',
    title: 'Rotate refresh tokens on every refresh',
    status: 'done',
    domain: 'authentication',
    agent: 'agent-01',
    created: '2026-05-13T10:00:00Z',
    closed: '2026-05-14T09:55:00Z',
    scope: 'src/auth/refresh.py',
    acceptance: ['Old token invalidated on use', 'Family revoked on replay attempt'],
  },
  {
    id: 'WI-bill-002',
    gapId: 'GAP-bill-003',
    title: 'Downgrades take effect at period end, not immediately',
    status: 'done',
    domain: 'billing',
    agent: 'agent-02',
    created: '2026-05-13T14:00:00Z',
    closed: '2026-05-14T08:30:00Z',
    scope: 'src/billing/subscription.py',
    acceptance: ['Downgrade flag stored', 'Tier swap at next renewal'],
  },
  {
    id: 'WI-trans-003',
    gapId: 'GAP-trans-003',
    title: 'Reject uploads >4hr at the boundary',
    status: 'done',
    domain: 'transcription',
    agent: 'agent-04',
    created: '2026-05-13T13:00:00Z',
    closed: '2026-05-14T07:12:00Z',
    scope: 'src/api/upload.py',
    acceptance: ['Duration probed before scheduling', 'Returns 413 with clear message'],
  },
];

/* ------------------------------------------------------------
   Activity stream
   ------------------------------------------------------------ */

const ACTIVITY = [
  { t: '10:41:08', agent: 'cc-main',    kind: 'in',   msg: 'editing <span class="ref">src/auth/admin.py:142</span> — adding MFA check' },
  { t: '10:40:52', agent: 'cc-main',    kind: 'in',   msg: 'running <b>pytest tests/auth/test_admin.py -k mfa</b>' },
  { t: '10:40:14', agent: 'cc-audit',   kind: 'in',   msg: 'wrote <span class="ref">.sdd/work-items/WI-trans-001.md</span> — note: backoff tests passing' },
  { t: '10:39:30', agent: 'cc-billing', kind: 'note', msg: 'WI-bill-001 blocked — waiting on TGT-014' },
  { t: '10:38:11', agent: 'cc-main',    kind: 'in',   msg: 'read <span class="ref">.sdd/specs/SPEC-auth.md</span>' },
  { t: '10:35:02', agent: 'cc-main',    kind: 'in',   msg: 'started <b>WI-auth-001</b> — Add MFA check to admin action handler' },
  { t: '10:32:44', agent: 'cc-audit',   kind: 'in',   msg: 'updated <span class="ref">src/jobs/transcribe.py:201</span> — exponential schedule' },
  { t: '10:30:19', agent: 'cc-main',    kind: 'note', msg: 'archived <b>WI-auth-004</b> — refresh rotation closed' },
  { t: '10:28:00', agent: 'cc-main',    kind: 'in',   msg: 'committed <span class="ref">62 lines</span> — "auth: rotate refresh tokens on each use"' },
  { t: '10:25:30', agent: 'cc-billing', kind: 'in',   msg: 'reading Stripe webhook docs for grace period flow' },
  { t: '10:22:14', agent: 'cc-audit',   kind: 'in',   msg: 'running <b>pytest tests/jobs/test_retry.py</b> — 14 passed' },
  { t: '10:19:00', agent: 'cc-main',    kind: 'note', msg: 'noticed TGT-011 awaiting user input' },
  { t: '10:18:42', agent: 'cc-main',    kind: 'in',   msg: 'wrote agent dialog turn on <b>TGT-011</b>' },
  { t: '10:15:00', agent: 'cc-audit',   kind: 'in',   msg: 'started <b>WI-trans-001</b> — Replace linear retry backoff' },
  { t: '10:11:33', agent: 'cc-main',    kind: 'note', msg: 'completed <b>WI-bill-002</b> — period-end downgrades shipped' },
  { t: '10:09:01', agent: 'cc-main',    kind: 'in',   msg: 'committed <span class="ref">88 lines</span> — "billing: downgrade at period end"' },
  { t: '10:02:14', agent: 'cc-main',    kind: 'in',   msg: 'flagged stale audit on billing domain (a3f→c4e1)' },
  { t: '09:58:00', agent: 'cc-billing', kind: 'in',   msg: 'wrote <span class="ref">src/billing/grace.py:1-44</span>' },
  { t: '09:55:12', agent: 'cc-main',    kind: 'note', msg: 'closed <b>WI-auth-004</b> (gap GAP-auth-004 → archive)' },
  { t: '09:51:00', agent: 'cc-audit',   kind: 'in',   msg: 'spec-audit pass on transcription domain (4 items checked)' },
  { t: '09:48:23', agent: 'cc-main',    kind: 'err',  msg: '<b>test failure</b> in tests/auth/test_admin.py::test_mfa_missing — retrying' },
  { t: '09:45:00', agent: 'cc-main',    kind: 'in',   msg: 'opened <span class="ref">src/auth/admin.py</span>' },
];

window.SDD = { NOW, fmtAgo, AGENTS, WORKSPACES, SPECS, TARGETS, GAPS, WORK_ITEMS, ACTIVITY };
